FROM node:18-alpine

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

#  archivo de dependencias 
COPY package*.json ./

#  Instala las dependencias
RUN npm install

#  El resto de archivos
COPY . .

# Puerto
EXPOSE 3000

# Comando que se ejecutará al iniciar el contenedor
CMD ["node", "server.js"]